# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QUIZ.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Answer = QtWidgets.QComboBox(self.centralwidget)
        self.Answer.setGeometry(QtCore.QRect(230, 220, 69, 22))
        self.Answer.setObjectName("Answer")
        self.Question = QtWidgets.QLabel(self.centralwidget)
        self.Question.setGeometry(QtCore.QRect(240, 140, 47, 13))
        self.Question.setObjectName("Question")
        self.NEXT = QtWidgets.QPushButton(self.centralwidget)
        self.NEXT.setGeometry(QtCore.QRect(540, 380, 75, 23))
        self.NEXT.setObjectName("NEXT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Question.setText(_translate("MainWindow", "TextLabel"))
        self.NEXT.setText(_translate("MainWindow", "NEXT"))
