# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeAmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(60, 30, 731, 521))
        self.tab.setObjectName("tab")
        self.Add = QtWidgets.QWidget()
        self.Add.setObjectName("Add")
        self.pushButton = QtWidgets.QPushButton(self.Add)
        self.pushButton.setGeometry(QtCore.QRect(310, 300, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.Add_2 = QtWidgets.QPushButton(self.Add)
        self.Add_2.setGeometry(QtCore.QRect(150, 300, 75, 23))
        self.Add_2.setObjectName("Add_2")
        self.ID_lop = QtWidgets.QLineEdit(self.Add)
        self.ID_lop.setGeometry(QtCore.QRect(150, 110, 231, 20))
        self.ID_lop.setObjectName("ID_lop")
        self.ten_lop = QtWidgets.QLineEdit(self.Add)
        self.ten_lop.setGeometry(QtCore.QRect(150, 150, 231, 20))
        self.ten_lop.setObjectName("ten_lop")
        self.ID_cau_hoi = QtWidgets.QLineEdit(self.Add)
        self.ID_cau_hoi.setGeometry(QtCore.QRect(150, 180, 231, 20))
        self.ID_cau_hoi.setObjectName("ID_cau_hoi")
        self.tab.addTab(self.Add, "")
        self.Update = QtWidgets.QWidget()
        self.Update.setObjectName("Update")
        self.tab.addTab(self.Update, "")
        self.Delete = QtWidgets.QWidget()
        self.Delete.setObjectName("Delete")
        self.tab.addTab(self.Delete, "")
        self.ShowAll = QtWidgets.QWidget()
        self.ShowAll.setObjectName("ShowAll")
        self.tab.addTab(self.ShowAll, "")
        self.AddStudent = QtWidgets.QWidget()
        self.AddStudent.setObjectName("AddStudent")
        self.tab.addTab(self.AddStudent, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Clear"))
        self.Add_2.setText(_translate("MainWindow", "Add"))
        self.ID_lop.setPlaceholderText(_translate("MainWindow", "ID_lop"))
        self.ten_lop.setPlaceholderText(_translate("MainWindow", "ten_lop"))
        self.ID_cau_hoi.setPlaceholderText(_translate("MainWindow", "ID_cau_hoi"))
        self.tab.setTabText(self.tab.indexOf(self.Add), _translate("MainWindow", "Add"))
        self.tab.setTabText(self.tab.indexOf(self.Update), _translate("MainWindow", "Update"))
        self.tab.setTabText(self.tab.indexOf(self.Delete), _translate("MainWindow", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.ShowAll), _translate("MainWindow", "ShowAll"))
        self.tab.setTabText(self.tab.indexOf(self.AddStudent), _translate("MainWindow", "AddStudent"))
