# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.student = QtWidgets.QTabWidget(self.centralwidget)
        self.student.setGeometry(QtCore.QRect(30, 30, 951, 611))
        self.student.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.student.setObjectName("student")
        self.studentprofile = QtWidgets.QWidget()
        self.studentprofile.setObjectName("studentprofile")
        self.title = QtWidgets.QLabel(self.studentprofile)
        self.title.setGeometry(QtCore.QRect(320, 20, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.masv = QtWidgets.QLabel(self.studentprofile)
        self.masv.setGeometry(QtCore.QRect(100, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.masv.setFont(font)
        self.masv.setObjectName("masv")
        self.hosv = QtWidgets.QLabel(self.studentprofile)
        self.hosv.setGeometry(QtCore.QRect(100, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hosv.setFont(font)
        self.hosv.setObjectName("hosv")
        self.tensv = QtWidgets.QLabel(self.studentprofile)
        self.tensv.setGeometry(QtCore.QRect(100, 220, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tensv.setFont(font)
        self.tensv.setObjectName("tensv")
        self.phai = QtWidgets.QLabel(self.studentprofile)
        self.phai.setGeometry(QtCore.QRect(100, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phai.setFont(font)
        self.phai.setObjectName("phai")
        self.ngaysinh = QtWidgets.QLabel(self.studentprofile)
        self.ngaysinh.setGeometry(QtCore.QRect(100, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ngaysinh.setFont(font)
        self.ngaysinh.setObjectName("ngaysinh")
        self.noisinh = QtWidgets.QLabel(self.studentprofile)
        self.noisinh.setGeometry(QtCore.QRect(100, 400, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noisinh.setFont(font)
        self.noisinh.setObjectName("noisinh")
        self.tenlop = QtWidgets.QLabel(self.studentprofile)
        self.tenlop.setGeometry(QtCore.QRect(100, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tenlop.setFont(font)
        self.tenlop.setObjectName("tenlop")
        self.password = QtWidgets.QLabel(self.studentprofile)
        self.password.setGeometry(QtCore.QRect(100, 520, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.showmasv = QtWidgets.QTextBrowser(self.studentprofile)
        self.showmasv.setGeometry(QtCore.QRect(260, 100, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showmasv.setFont(font)
        self.showmasv.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.showmasv.setObjectName("showmasv")
        self.showhosv = QtWidgets.QTextBrowser(self.studentprofile)
        self.showhosv.setGeometry(QtCore.QRect(260, 160, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showhosv.setFont(font)
        self.showhosv.setObjectName("showhosv")
        self.showtensv = QtWidgets.QTextBrowser(self.studentprofile)
        self.showtensv.setGeometry(QtCore.QRect(260, 220, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showtensv.setFont(font)
        self.showtensv.setObjectName("showtensv")
        self.showphai = QtWidgets.QTextBrowser(self.studentprofile)
        self.showphai.setGeometry(QtCore.QRect(260, 270, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showphai.setFont(font)
        self.showphai.setObjectName("showphai")
        self.showngaysinh = QtWidgets.QTextBrowser(self.studentprofile)
        self.showngaysinh.setGeometry(QtCore.QRect(260, 330, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showngaysinh.setFont(font)
        self.showngaysinh.setObjectName("showngaysinh")
        self.shownoisinh = QtWidgets.QTextBrowser(self.studentprofile)
        self.shownoisinh.setGeometry(QtCore.QRect(260, 390, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shownoisinh.setFont(font)
        self.shownoisinh.setObjectName("shownoisinh")
        self.showtenlop = QtWidgets.QTextBrowser(self.studentprofile)
        self.showtenlop.setGeometry(QtCore.QRect(260, 450, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showtenlop.setFont(font)
        self.showtenlop.setObjectName("showtenlop")
        self.showpassword = QtWidgets.QTextBrowser(self.studentprofile)
        self.showpassword.setGeometry(QtCore.QRect(260, 520, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.showpassword.setFont(font)
        self.showpassword.setObjectName("showpassword")
        self.student.addTab(self.studentprofile, "")
        self.taketest = QtWidgets.QWidget()
        self.taketest.setObjectName("taketest")
        self.title_2 = QtWidgets.QLabel(self.taketest)
        self.title_2.setGeometry(QtCore.QRect(340, 120, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_2.setFont(font)
        self.title_2.setObjectName("title_2")
        self.inputmamh = QtWidgets.QTextBrowser(self.taketest)
        self.inputmamh.setGeometry(QtCore.QRect(220, 230, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inputmamh.setFont(font)
        self.inputmamh.setObjectName("inputmamh")
        self.buttonvaothi = QtWidgets.QPushButton(self.taketest)
        self.buttonvaothi.setGeometry(QtCore.QRect(330, 350, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonvaothi.setFont(font)
        self.buttonvaothi.setObjectName("buttonvaothi")
        self.student.addTab(self.taketest, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.student.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Student\'s Profile"))
        self.masv.setText(_translate("MainWindow", "Ma Sinh Vien:"))
        self.hosv.setText(_translate("MainWindow", "Ho Sinh Vien:"))
        self.tensv.setText(_translate("MainWindow", "Ten Sinh Vien:"))
        self.phai.setText(_translate("MainWindow", "Gioi Tinh:"))
        self.ngaysinh.setText(_translate("MainWindow", "Ngay Sinh:"))
        self.noisinh.setText(_translate("MainWindow", "Noi Sinh:"))
        self.tenlop.setText(_translate("MainWindow", "Ten Lop:"))
        self.password.setText(_translate("MainWindow", "Password:"))
        self.showmasv.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showhosv.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showtensv.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showphai.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showngaysinh.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.shownoisinh.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showtenlop.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.showpassword.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.student.setTabText(self.student.indexOf(self.studentprofile), _translate("MainWindow", "Tab 1"))
        self.title_2.setText(_translate("MainWindow", "Nhap Ma Mon Hoc"))
        self.inputmamh.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.buttonvaothi.setText(_translate("MainWindow", "Vao Thi"))
        self.student.setTabText(self.student.indexOf(self.taketest), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
