# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendEmail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QButtonSend = QtWidgets.QPushButton(self.centralwidget)
        self.QButtonSend.setGeometry(QtCore.QRect(230, 270, 75, 23))
        self.QButtonSend.setObjectName("QButtonSend")
        self.QButtonClear = QtWidgets.QPushButton(self.centralwidget)
        self.QButtonClear.setGeometry(QtCore.QRect(390, 270, 75, 23))
        self.QButtonClear.setObjectName("QButtonClear")
        self.QLineEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.QLineEmail.setGeometry(QtCore.QRect(230, 230, 301, 20))
        self.QLineEmail.setObjectName("QLineEmail")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 230, 47, 16))
        self.label.setObjectName("label")
        self.QButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.QButtonBack.setGeometry(QtCore.QRect(540, 440, 91, 61))
        self.QButtonBack.setObjectName("QButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.QButtonSend.setText(_translate("MainWindow", "Send"))
        self.QButtonClear.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Email:"))
        self.QButtonBack.setText(_translate("MainWindow", "BACK"))
